[template]

[hooks]
pre = ["init.rhai", "../common.rhai"]
post = ["conditional-files.rhai"]

[placeholders]
is_fullstack = { prompt = "Do you want to use Dioxus Fullstack?", default = false, type = "bool" }
is_router = { prompt = "Do you want to use Dioxus Router?", default = false, type = "bool" }
is_tailwind = { prompt = "Do you want to use Tailwind CSS?", default = false, type = "bool" }
